# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.IntegerField(default=40),
        ),
    ]
